import fs from 'node:fs/promises';
export const root='D:/Pathcraft-AI/deliverables/tangjung_0_5_5_research_2026-09-07/worker';
const bridge=JSON.parse(await fs.readFile('D:/Pathcraft-AI/.tmp/tangjung_055_mcp_bridge.json','utf8'));
export async function run(code){
 const res=await fetch(bridge.url,{method:'POST',headers:{'content-type':'application/json','x-task-token':bridge.token},body:JSON.stringify({method:'tools/call',params:{name:'browser_run_code_unsafe',arguments:{code}}})});
 if(!res.ok)throw Error('Playwright bridge HTTP '+res.status);
 const r=await res.json(); const t=r.content.filter(c=>c.type==='text').map(c=>c.text).join('\n');
 if(r.isError)throw Error(t);return JSON.parse(t.split('### Result\n')[1].split('\n###')[0]);
}
export async function pr(code){return run(`async(page)=>{var p=page.context().pages().find(p=>p.url().endsWith('#tangjung-worker-review'));if(!p)throw Error('worker tab missing');${code}}`);}
export async function save(name,data){await fs.writeFile(root+'/'+name,typeof data==='string'?data:JSON.stringify(data,null,2));}
export async function meta(){return pr(`return await p.evaluate(()=>{var r=document.querySelector('#movie_player').getPlayerResponse();var m=r.microformat?.playerMicroformatRenderer;var v=document.querySelector('video');v.muted=true;v.pause();return {videoId:r.videoDetails?.videoId,title:r.videoDetails?.title,description:r.videoDetails?.shortDescription,duration:Number(r.videoDetails?.lengthSeconds),mediaDuration:v.duration,publishDate:m?.publishDate,uploadDate:m?.uploadDate,isLiveContent:r.videoDetails?.isLiveContent,status:r.playabilityStatus?.status,captions:r.captions?.playerCaptionsTracklistRenderer?.captionTracks?.map(t=>({name:t.name,languageCode:t.languageCode,kind:t.kind}))||[],wall:new Date().toISOString()};});`);}
export async function go(id){await pr(`await p.goto('https://www.youtube.com/watch?v=${id}#tangjung-worker-review',{timeout:15000});await p.waitForFunction(id=>document.querySelector('#movie_player')?.getPlayerResponse?.()?.videoDetails?.videoId===id,'${id}',{timeout:10000});return p.url();`);const s=await meta();await save('evidence/'+id+'_metadata.json',s);return s;}
export async function snap(t,label){
 const r=await pr(`await p.evaluate(t=>{var v=document.querySelector('video');v.muted=true;v.pause();v.currentTime=t;},${t});await p.waitForFunction(t=>{var v=document.querySelector('video');return !v.seeking&&v.readyState>=2&&Math.abs(v.currentTime-t)<.5;},${t},{timeout:10000});var state=await p.evaluate(()=>{var v=document.querySelector('video');return {videoId:document.querySelector('#movie_player').getPlayerResponse().videoDetails.videoId,time:v.currentTime,paused:v.paused,muted:v.muted,width:v.videoWidth,height:v.videoHeight,wall:new Date().toISOString()};});return {...state,base64:(await p.locator('video').screenshot({type:'jpeg',quality:94,timeout:8000})).toString('base64')};`);
 const file='evidence/'+r.videoId+'_'+String(t).replace('.','p')+'_'+label+'.jpg';await fs.writeFile(root+'/'+file,Buffer.from(r.base64,'base64'));
 const o={...r,base64:undefined,requestedTime:t,method:'paused_frame_inspection',evidence:file};const obs=JSON.parse(await fs.readFile(root+'/observations.json','utf8').catch(()=>'[]'));obs.push(o);await save('observations.json',obs);return o;
}
export async function transcript(){return pr(`return await p.locator('transcript-segment-view-model').evaluateAll(ss=>ss.map(s=>({time:s.querySelector('.ytwTranscriptSegmentViewModelTimestamp')?.textContent,text:s.querySelector('span[role=text]')?.textContent})));`);}
export async function burst(start,label,count=8,rate=.5){
 const r=await pr(`await p.locator('video').scrollIntoViewIfNeeded({timeout:5000});await p.evaluate(t=>{var v=document.querySelector('video');v.pause();v.muted=true;v.currentTime=t;},${start});await p.waitForFunction(()=>!document.querySelector('video').seeking,null,{timeout:10000});await p.evaluate(async()=>{var v=document.querySelector('video');v.playbackRate=${rate};await v.play();});var frames=[];for(var i=0;i<${count};i++){await p.waitForTimeout(650);var before=await p.evaluate(()=>{var v=document.querySelector('video');return {videoId:document.querySelector('#movie_player').getPlayerResponse().videoDetails.videoId,time:v.currentTime,paused:v.paused,muted:v.muted,seeking:v.seeking,wall:Date.now()};});var buf=await p.locator('video').screenshot({type:'jpeg',quality:90,timeout:8000});var after=await p.evaluate(()=>document.querySelector('video').currentTime);frames.push({...before,after,base64:buf.toString('base64')});}var end=await p.evaluate(()=>{var v=document.querySelector('video');v.pause();v.playbackRate=1;return v.currentTime;});return {start:${start},end,rate:${rate},frames};`);
 const obs=JSON.parse(await fs.readFile(root+'/observations.json','utf8'));
 for(let i=0;i<r.frames.length;i++){const f=r.frames[i];const evidence='evidence/'+f.videoId+'_'+label+'_'+i+'.jpg';await fs.writeFile(root+'/'+evidence,Buffer.from(f.base64,'base64'));delete f.base64;f.evidence=evidence;f.method='playback_frame_sequence';obs.push(f);}
 await save('observations.json',obs);await save('evidence/'+r.frames[0].videoId+'_'+label+'_sequence.json',{...r,continuousObservedSeconds:0,note:'모든 원본 프레임이 관찰된 것은 아니며 각 캡처 앞뒤 currentTime 범위와 프레임 간 미관찰 간격을 보존함'});return r;
}
